### ISSUE TITLE
установка карточки

### ISSUE THREAD

**Issue by alexanderznamensky** [turbulator/pandora-cas-card#1]
в описание хорошо бы добавить, что в configuration.yaml надо указать путь к карточке:
```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/pandora-cas-card/pandora-cas-card.js
      type: module
```

Ждем продолжение!
